### ISSUE TITLE
Test running endless, no timeouts, no errors

### ISSUE THREAD

**Issue by ixcefau** [mandziak-nv/vscode-cucumber-js-runner#2]
Hello, I am using the official Cucumber.io extension and Playwright together with this extension to execute my feature files as tests.

If I run the feature file via cucumber-js script the file executes as intended. But any time I want to run it via the extension the test runner just cycles indefinitely without terminating. No errors, no timeouts, nothing. Test Coverage at 0.00%.

Is there any way to to debug this?

```
...
    "cucumber.features": [
        "features/*.feature",
    ],
    "cucumber.glue": [
        "features/step_definitions/*.ts",
    ],
    "totalTypeScript.hiddenTips": [
        "variable-type-annotation",
        "typing-function-parameters",
        "basic-types"
    ],
    "javascript.updateImportsOnFileMove.enabled": "always",
    "cucumber.parameterTypes": [
    ],
    "cucumber_runner.cli_options":[
        "--profile",
        "parallel",
        "--tags",
        "@test"
      ],
    "cucumber_runner.env_variables": {
        "BROWSER": "chromium",
        "DEVICE": "desktop"
      },
    "cucumber_runner.features": [
        "features/*.feature"
    ]
...
```

Test Result:

> Scenario: "Login user"
> 
> Executing command:
> BROWSER=...... DEVICE=...... node ./node_modules/.bin/cucumber-js features/*.feature --name "^Login user$" --profile parallel --tags \@\test
> *  The test case did not report any output. 

<details>
<summary> Plugins </summary>

```
Visual Studio Code

Version: 1.86.1 (user setup)
Commit: 31c37ee8f63491495ac49e43b8544550fbae4533
Date: 2024-02-07T09:08:20.941Z (5 days ago)
Electron: 27.2.3
ElectronBuildId: 26495564
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.22631
```

```
Name: Playwright Test for VSCode
Id: ms-playwright.playwright
Description: Run Playwright Test tests in Visual Studio Code.
Version: 1.0.22
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-playwright.playwright
```
```
Name: Cucumber JS Test Runner
Id: nick-mandziak.vscode-cucumber-js-runner
Description: Cucumber JS Test Runner for VS Code
Version: 1.83.1
Publisher: Nick Mandziak
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=nick-mandziak.vscode-cucumber-js-runner
```
```
Name: Cucumber
Id: CucumberOpen.cucumber-official
Description: Cucumber for Visual Studio Code
Version: 1.8.1
Publisher: Cucumber
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=CucumberOpen.cucumber-official
```
</details>

**Comment by mandziak-nv** [comment]
Should be fixed after v1.89

**Comment by aristotelos** [comment]
@mandziak-nv I have the same issue still, running with v1.89.2. Is there any way to inspect logging?
